N trees experiment
pyensemble/wildwood pull request #41
Opened 2021-04-21 09:08 UTC by imerad

This PR addresses issue #37 adding a file ``n_tree_experiment.py`` performing the experiment with all considered random forest algorithms and a notebook ``n_trees_experiment.ipynb`` generating a figure.

Additional tiny modification to wildwood/forest.py to allow passing categorical features at fit time.

Also small modification to dataset.py to allow extracting data into pandas dataframe

2021-04-29 19:38 UTC, stephanegaiffas requested changes

2021-04-29 19:38 UTC, stephanegaiffas commented on wildwood/dataset/dataset.py
> +        if self.pd_df_categories:
Pourquoi on fait ca ? C'est pour avoir les X_train et X_test sous forme de dataframes avec les type category c'est ca ?

2021-04-29 19:38 UTC, stephanegaiffas commented on wildwood/forest.py
> +    def fit(self, X, y, sample_weight=None, categorical_features=None):
Euh pourquoi on a besoin de ca ? On passe categorical_features au constructeur normalement non ?

2021-04-30 08:18 UTC, imerad commented on wildwood/dataset/dataset.py
> +        if self.pd_df_categories:
Oui c'est ça

2021-04-30 08:20 UTC, imerad commented on wildwood/forest.py
> +    def fit(self, X, y, sample_weight=None, categorical_features=None):
C'est plus commode de pouvoir passer cette option lors de l'appel à fit, surtout dans les boucles d'un script de benchmark lorsqu'on charge plusieurs fois le classifieur pour différents datasets, en plus, presque tous les autres algorithmes le permettent et ça ne complique pas vraiment le code

2021-05-03 14:14 UTC, stephanegaiffas approved these changes

2021-05-03 14:15 UTC, merged